services:
  - type: web
    name: menufic
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SKIP_ENV_VALIDATION
        value: "false"
